# Generated by Django 2.0.7 on 2018-07-27 06:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180727_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createed_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 27, 6, 41, 7, 449705, tzinfo=utc)),
        ),
    ]
