# Generated by Django 2.0.7 on 2018-07-27 06:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180727_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createed_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 27, 6, 43, 13, 387884, tzinfo=utc)),
        ),
    ]
