# Generated by Django 2.0.7 on 2018-07-27 06:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180727_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createed_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 27, 6, 45, 17, 818808, tzinfo=utc)),
        ),
    ]
